export const tests = [
  {
    id: 1,
    title: "HTML",
    link: "/html",
    chips: ["Теория"],
  },
  {
    id: 2,
    title: "CSS",
    link: "/css",
    chips: ["Теория"],
  },
  {
    id: 3,
    title: "Git",
    link: "/git",
    chips: ["Теория"],
  },
  {
    id: 4,
    title: "JavaScript",
    link: "/javascript",
    chips: ["Теория"],
  },
  {
    id: 5,
    title: "Английский",
    link: "/english",
    chips: ["Теория"],
  },
  {
    id: 6,
    title: "API",
    link: "/api",
    chips: ["Теория"],
  },
  {
    id: 7,
    title: "Agile Project Management",
    link: "/agile",
    chips: ["Теория"],
  },
  {
    id: 8,
    title: "AutoCAD",
    link: "/autocad",
    chips: ["Теория"],
  },
  {
    id: 9,
    title: "C#",
    link: "/C#",
    chips: ["Теория", "Практика"],
  },
  {
    id: 10,
    title: "C++",
    link: "/C++",
    chips: ["Теория", "Практика"],
  },
  {
    id: 11,
    title: "Docker",
    link: "/docker",
    chips: ["Теория"],
  },
  {
    id: 12,
    title: "Golang",
    link: "/golang",
    chips: ["Теория", "Практика"],
  },
  {
    id: 13,
    title: "HR-аналитика",
    link: "/hr-analitycs",
    chips: ["Теория"],
  },
  {
    id: 14,
    title: "Java",
    link: "/java",
    chips: ["Теория", "Практика"],
  },
  {
    id: 15,
    title: "Linux",
    link: "/linux",
    chips: ["Теория"],
  },
  {
    id: 16,
    title: "MS Excel",
    link: "/ms-excel",
    chips: ["Теория"],
  },
  {
    id: 17,
    title: "OKR",
    link: "/okr",
    chips: ["Теория"],
  },
  {
    id: 18,
    title: "PHP",
    link: "/php",
    chips: ["Теория", "Практика"],
  },
  {
    id: 19,
    title: "PostgreSQL",
    link: "/postgresSQL",
    chips: ["Теория"],
  },
  {
    id: 20,
    title: "Python",
    link: "/python",
    chips: ["Теория", "Практика"],
  },
  {
    id: 21,
    title: "SQL",
    link: "/sql",
    chips: ["Теория", "Практика"],
  },
  {
    id: 22,
    title: "Scrum",
    link: "/scrum",
    chips: ["Теория"],
  },
  {
    id: 23,
    title: "Алгоритмы и структуры данных",
    link: "/algoritms",
    chips: ["Теория"],
  },
  {
    id: 24,
    title: "Копирайтинг",
    link: "/copywriting",
    chips: ["Теория"],
  },
  {
    id: 25,
    title: "Математическая статистика",
    link: "/math-statistics",
    chips: ["Теория"],
  },
  {
    id: 26,
    title: "Машинное обучение",
    link: "/machine-learning",
    chips: ["Теория"],
  },
  {
    id: 27,
    title: "ООП",
    link: "/oop",
    chips: ["Теория"],
  },
  {
    id: 28,
    title: "Регрессионное тестирование",
    link: "/regression-testing",
    chips: ["Теория"],
  },
  {
    id: 29,
    title: "Функциональное тестирование",
    link: "/functional-testing",
    chips: ["Теория"],
  },
] as const;
