export const projects = [
  {
    img: "/projects/akystik.png",
    title: "Акустик",
    subtitle: "Магазин слуховых аппаратов",
    descriptions:
      "Комплексная платформа для подбора и покупки слуховых аппаратов с интеллектуальной системой диагностики слуха и персонализированными рекомендациями",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Redux",
      "Scss",
      "Framer Motion",
      "Swiper",
      "Yup",
      "React Query",
      "React Hook Form",
    ],
    tags: [
      "Магазин",
      "Слуховые аппараты",
      "Админ панель",
      "Медицина",
      "Клиника",
    ],
    link: "https://akystik.ru",
    github: null,
  },
  {
    img: "/projects/boost.png",
    title: "Boost",
    subtitle: "Платформа для подготовки к ОГЭ/ЕГЭ",
    descriptions:
      "Инновационная образовательная экосистема с адаптивным обучением, AI-репетитором и интерактивными симуляторами экзаменов для максимальной эффективности подготовки",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Jotai",
      "Redux Toolkit",
      "Tanstack Query",
      "Tailwind",
      "Framer Motion",
      "Zod",
      "React Hook Form",
      "FSD",
    ],
    tags: ["Платформа", "Подготовка", "Личный кабинет", "Курсы", "ОГЭ", "ЕГЭ"],
    link: "https://boost-ai.ru/",
    github: null,
  },
  {
    img: "/projects/fitsharing.png",
    title: "Fitsharing",
    subtitle: "Аренда тренажеров",
    descriptions:
      "P2P маркетплейс для аренды спортивного оборудования с системой доставки, страхования и онлайн-консультаций от фитнес-экспертов",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Jotai",
      "Redux Toolkit",
      "Tanstack Query",
      "Tailwind",
      "Framer Motion",
      "Zod",
      "React Hook Form",
    ],
    tags: ["Аренда", "Тренажеры", "Админ панель", "Маркетплейс", "Фитнес"],
    link: "https://fitsharing.ru/",
    github: null,
  },
  {
    img: "/projects/hite-bbq.png",
    title: "Hite BBQ",
    subtitle: "Сайт ресторана для заказа еды",
    descriptions:
      "Премиум платформа для заказа авторских барбекю-блюд с системой отслеживания готовки в реальном времени и технологией AR-просмотра блюд",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Zustand",
      "Tanstack Query",
      "Tailwind",
      "Framer Motion",
      "Zod",
      "React Hook Form",
      "FSD",
    ],
    tags: ["Ресторан", "Заказ", "Доставка", "Барбекю", "Премиум"],
    link: "",
    github: null,
  },
  {
    img: "/projects/ibankrot.png",
    title: "IBankrot",
    subtitle: "Юридическая помощь для оформления банкротства",
    descriptions:
      "Цифровой юрист-ассистент с AI-анализом финансовой ситуации и автоматическим составлением документов для процедуры банкротства физических лиц",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Zustand",
      "Axios",
      "Tailwind",
      "Framer Motion",
      "Yup",
      "React Hook Form",
    ],
    tags: ["Юридическая помощь", "Банкротство", "Оформление", "AI", "Финансы"],
    link: "https://ibankrot.ru/",
    github: null,
  },
  {
    img: "/projects/result.png",
    title: "Result",
    subtitle: "Платформа для обучения на Frontend",
    descriptions:
      "Интерактивная среда обучения фронтенд-разработке с живыми проектами, системой код-ревью и интеграцией с реальными стартапами для практики",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Zustand",
      "Axios",
      "Tailwind",
      "Framer Motion",
      "Yup",
      "React Hook Form",
      "FSD",
    ],
    tags: ["Платформа", "Обучение", "Frontend", "Разработка", "Код-ревью"],
    link: "https://result.school/",
    github: null,
  },
  {
    img: "/projects/taxi-ritm.png",
    title: "Taxi Ritm",
    subtitle: "Такси Ритм — крупнейший таксопарк в Москве",
    descriptions:
      "Умная система управления корпоративным таксопарком с AI-оптимизацией маршрутов, телеметрией и предиктивной аналитикой спроса",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Zustand",
      "Axios",
      "Tailwind",
      "Framer Motion",
      "Yup",
      "React Hook Form",
      "FSD",
    ],
    tags: ["Такси", "Логистика", "AI", "Корпоративный", "Оптимизация"],
    link: "https://www.taxi-ritm.ru/",
    github: null,
  },
];
