export const Projects = [
  {
    img: "/projects/akystik.png",
    title: "Акустик",
    descriptions: "Магазин слуховых аппаратов",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Redux",
      "Scss",
      "Framer Motion",
      "Swiper",
      "Yup",
      "React Query",
      "React Hook Form",
    ],
    tags: [
      "Магазин",
      "Слуховые аппараты",
      "Админ панель",
      "Медицина",
      "Клиника",
    ],
    link: "",
    github: null,
  },
  {
    img: "/projects/boost.png",
    title: "Boost",
    descriptions: "Платформа для подготовки к ОГЭ/ЕГЭ",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Jotai",
      "Redux Toolkit",
      "Tanstack Query",
      "Tailwind",
      "Framer Motion",
      "Zod",
      "React Hook Form",
      "FSD",
    ],
    tags: ["Платформа", "Подготовка", "Личный кабинет", "Курсы", "ОГЭ", "ЕГЭ"],
    link: "",
    github: null,
  },
  {
    img: "/projects/fitsharing.png",
    title: "Fitsharing",
    descriptions: "Аренда тренажеров",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Jotai",
      "Redux Toolkit",
      "Tanstack Query",
      "Tailwind",
      "Framer Motion",
      "Zod",
      "React Hook Form",
    ],
    tags: ["Аренда", "Тренажеры", "Админ панель", "Курсы", "ОГЭ", "ЕГЭ"],
    link: "",
    github: null,
  },
  {
    img: "/projects/hite-bbq.png",
    title: "Hite BBQ",
    descriptions: "Сайт ресторана для заказа еды",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Zustand",
      "Tanstack Query",
      "Tailwind",
      "Framer Motion",
      "Zod",
      "React Hook Form",
      "FSD",
    ],
    tags: ["Ресторан", "Заказ", "Доставка"],
    link: "",
    github: null,
  },
  {
    img: "/projects/ibankrot.png",
    title: "IBankrot",
    descriptions: "Юридическая помощь для оформления банкротства",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Zustand",
      "Axios",
      "Tailwind",
      "Framer Motion",
      "Yup",
      "React Hook Form",
    ],
    tags: ["Юридическая помощь", "Банкротство", "Оформление"],
    link: "",
    github: null,
  },
  {
    img: "/projects/result.png",
    title: "Result",
    descriptions: "Платформа для обучения на Frontend",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Zustand",
      "Axios",
      "Tailwind",
      "Framer Motion",
      "Yup",
      "React Hook Form",
      "FSD",
    ],
    tags: ["Платформа", "Подготовка", "Курсы", "ОГЭ", "ЕГЭ"],
    link: "",
    github: null,
  },
  {
    img: "/projects/taxi-ritm.png",
    title: "Taxi Ritm",
    descriptions: "Такси Ритм — крупнейший таксопарк в Москве",
    stack: [
      "NextJS",
      "React",
      "Typescript",
      "Zustand",
      "Axios",
      "Tailwind",
      "Framer Motion",
      "Yup",
      "React Hook Form",
      "FSD",
    ],
    tags: ["Платформа", "Подготовка", "Курсы", "ОГЭ", "ЕГЭ"],
    link: "",
    github: null,
  },
];
