export const services = [
  {
    id: 1,
    title: "Разработка сайта",
    subtitle: "Корпоративный сайт под ключ",
    price: 1500,
    discount: null,
    isPopular: false,
    perHour: true,
  },
  {
    id: 2,
    title: "Интернет-магазин",
    subtitle: "Полный цикл разработки с интеграцией платежей",
    price: 3200,
    discount: 15,
    isPopular: true,
    perHour: false,
  },
  {
    id: 3,
    title: "Мобильное приложение",
    subtitle: "Кроссплатформенное приложение для iOS и Android",
    price: 4500,
    discount: 35,
    isPopular: true,
    perHour: false,
  },
  {
    id: 4,
    title: "UI/UX дизайн",
    subtitle: "Проектирование пользовательских интерфейсов",
    price: 800,
    discount: 10,
    isPopular: false,
    perHour: false,
  },
  {
    id: 5,
    title: "Техническая поддержка",
    subtitle: "Ежемесячное обслуживание и мониторинг",
    price: 300,
    discount: null,
    isPopular: false,
    perHour: false,
  },
  {
    id: 6,
    title: "SEO-оптимизация",
    subtitle: "Продвижение в поисковых системах",
    price: 1200,
    discount: 20,
    isPopular: true,
    perHour: false,
  },
  {
    id: 7,
    title: "Веб-приложение",
    subtitle: "Сложное веб-приложение с базой данных",
    price: 5500,
    discount: 25,
    isPopular: false,
    perHour: false,
  },
  {
    id: 8,
    title: "Брендинг и айдентика",
    subtitle: "Разработка логотипа и фирменного стиля",
    price: 600,
    discount: 15,
    isPopular: false,
    perHour: false,
  },
  {
    id: 9,
    title: "Чат-бот для бизнеса",
    subtitle: "AI-бот для автоматизации продаж",
    price: 900,
    discount: 30,
    isPopular: true,
    perHour: false,
  },
  {
    id: 10,
    title: "Дашборд аналитики",
    subtitle: "Визуализация бизнес-показателей",
    price: 2000,
    discount: null,
    isPopular: false,
    perHour: false,
  },
];
